### PR TITLE
Add Typed PID Maker UI

### PR DESCRIPTION
**Pull request by Pfeil**
- [x] implement basic typed pid maker ui
  - [x] includes common header and config things 
- [x] attach to main page
- [x] Fix image aspect ratio on main page

Things I will not do in this PR, but in a later one:

- Adjust table style to the rest of the UI

### CODE REVIEW

**Comment by Pfeil** [comment]
Due to the different kind of images, the look is quiet different.

grafik

I see the following options:

1. Let it stay like it is. The card is of the same size, so we currently just take space we have.
2. At least change the background color (which is the CSS's default) to white or something.
3. Make all images in the same aspect ratio (with which background color?)

**Comment by ThomasJejkal** [comment]
> Due to the different kind of images, the look is quiet different.
> 
> grafik
> 
> I see the following options:
> 
> 1. Let it stay like it is. The card is of the same size, so we currently just take space we have.
> 2. At least change the background color (which is the CSS's default) to white or something.
> 3. Make all images in the same aspect ratio (with which background color?)

I personally tend to option 3.

**Comment by pjoKIT** [comment]
> I see the following options:
> 
>     1. Let it stay like it is. The card is of the same size, so we currently just take space we have. 
>     2. At least change the background color (which is the CSS's default) to white or something.
>     3. Make all images in the same aspect ratio (with which background color?)

I'm also in favor of the third option.

Do you mean the image background color? I would suggest a transparent background where feasible (i.e. in case of the Typed PID Maker logo). This should work as long as we do not make the website background color too garish.

**Comment by Pfeil** [comment]
> I'm also in favor of the third option.

Planning to do so :)

> Do you mean the image background color? I would suggest a transparent background where feasible (i.e. in case of the Typed PID Maker logo). This should work as long as we do not make the website background color too garish.

I mean the color shown behind the transparent background of the logo. I did not set any, so it is some default, probably by semantic-ui. I can set the color to anything, using CSS. While white looks nice, it also removes the card feeling a little.

**Comment by Pfeil** [comment]
This is how it looks like now. Looks fine for me. The gray background is a nice neutral somehow and probably fits for most logos to come. Feel free to merge.

---

Main page:

grafik

---

First version of the Typed PID Maker UI (better table styling is on the way, not for this PR :) )

grafik

**Pull request merged**
